version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - migrations

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - sqlclosecheck
    - misspell
    - bodyclose
    - noctx
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - unused
          - errcheck
          - funlen
          - goconst

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/squ1ky/pr-manager

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/squ1ky/pr-manager

  revive:
    confidence: 0.8
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: function-length
        arguments: [50, 0]
      - name: empty-lines
      - name: empty-block

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      format: colored-line-number
      path: stdout
  print-linter-name: true
  print-issued-lines: true
  sort-results: true